### ISSUE TITLE
Investigate if backward-compatibility can be maintained for update/delete across all controllers and scheduler

### ISSUE THREAD

**Issue by XiaoningDing** [futurewei-cloud/arktos#185]
<To add details>

**Comment by chenqianfzh** [comment]
As shown in https://github.com/futurewei-cloud/arktos/pull/191, The backward-compatibility of Update/UpdateStatus can be maintained by grabbing the tenant info from the Object info passed to the API of Update/UpdateStatus.

However, it is impossible for the Delete(). The cause is that the  the parameter passed to Delete() is ObjectName ( string type), which does not contain the info of the tenant.
