### ISSUE TITLE
tenant controller repeatedly attempts to create ns and other resources even if it's already done

### ISSUE THREAD

**Issue by pdgetrf** [futurewei-cloud/arktos#453]
tenant controller wakes up every 5 minutes and attempt to create resources such as ns, clusterroles and network objects without checking existence first. 
![image](https://user-images.githubusercontent.com/252020/86658831-3699ab80-bf9e-11ea-957a-326d65d7d604.png)

it is relying on error from creation to prevent duplication. if a tenant has already been provisioned at creation, tenant controller should probably skip it to prevent performance hit.

![image](https://user-images.githubusercontent.com/252020/86658160-af4c3800-bf9d-11ea-9a9a-770daa169967.png)

**Comment by Sindica** [comment]
Line 107: tenantInformer.Informer().AddEventHandlerWithResyncPeriod(

Generally AddEventHandler is used instead of AddEventHandlerWithResyncPeriod unless same events need to be periodically rechecked. Currently resyncPeriod is 5min. That's why it gets repeated event notification and tries create those objects every 5 min.
