### ISSUE TITLE
Workload-controller-manger log error: Current instance not in registry, needs restart error in workload-controller-manger.log

### ISSUE THREAD

**Issue by sonyafenge** [futurewei-cloud/arktos#659]
**What happened**:
```
I0830 20:35:04.394877       1 controller_framework.go:174] Got controller instance update massage. Updated Controller Type ReplicaSet, current controller instance type Deployment, key 4611686018427387904
I0830 20:35:04.394898       1 controller_framework.go:174] Got controller instance update massage. Updated Controller Type ReplicaSet, current controller instance type ReplicaSet, key 4611686018427387904
E0830 20:35:04.394937       1 controller_framework.go:360] Current instance not in registry. Controller type ReplicaSet, instance id replicaset-6202a115-3720-4e37-bb84-7a85929b9d8a, key 4611686018427387904. Needs restart
I0830 20:35:04.541697       1 replica_set.go:617] RS system/10o1cppt137t9jf4pn68pu14wohac82g-ns/10o1cppt137t9jf4pn68pu14wohac82g-pods-69c768c4cf hashkey 9059290195717984041 not in RSC range - key 4611686018427387904
I0830 20:35:04.563432       1 replica_set.go:617] RS system/10o1cppt137t9jf4pn68pu14wohac82g-ns/10o1cppt137t9jf4pn68pu14wohac82g-pods-69c768c4cf hashkey 9059290195717984041 not in RSC range - key 4611686018427387904
I0830 20:35:04.575070       1 replica_set.go:617] RS system/10o1cppt137t9jf4pn68pu14wohac82g-ns/10o1cppt137t9jf4pn68pu14wohac82g-pods-69c768c4cf hashkey 9059290195717984041 not in RSC range - key 4611686018427387904
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Logs are located under workload-controller-manger project at:  sonya-uswest2: /home/sonyali/logs/perf-test/gce-10000/arktos/0830-upgrade15000-3api-2wc-1etcd/logs/
**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Sindica** [comment]
This only affects log. No functional impact.

**Comment by panda98004** [comment]
Need to verify

**Comment by sonyafenge** [comment]
### 9/4/2020 [scalability][arktos][node10K][Fixverify] node10k-3a3c1e
Started a 10K nodes run with 3 apiserver, 3 workload, 1 etcd to verify this fix. Cluster crashed when create 100K -> 200K pods with issue: https://github.com/futurewei-cloud/arktos/issues/687. and there are still bunch of this error in workload-controller-manager.log
```
I0904 22:15:30.252843       1 controller_framework.go:174] Got controller instance update massage. Updated Controller Type Deployment, current controller instance type Deployment, key 9223372036854775807
E0904 22:15:30.252878       1 controller_framework.go:363] Current instance not in registry. Controller type Deployment, instance id deployment-543f0343-d5bb-4b74-81e1-848a429f6958, key 9223372036854775807. Needs restart
I0904 22:15:30.252974       1 controller_framework.go:174] Got controller instance update massage. Updated Controller Type Deployment, current controller instance type ReplicaSet, key 9223372036854775807
```
logs can be found under GCP project: workload-controller-manager:
```
sonya-useast1:  /home/sonyali/logs/perf-test/gce-10000/arktos/0904-node10k-3a2c1e 
```

**Comment by Sindica** [comment]
> ### 9/4/2020 [scalability][arktos][node10K][Fixverify] node10k-3a3c1e
> Started a 10K nodes run with 3 apiserver, 3 workload, 1 etcd to verify this fix. Cluster crashed when create 100K -> 200K pods with issue: #687. and there are still bunch of this error in workload-controller-manager.log
> 
> ```
> I0904 22:15:30.252843       1 controller_framework.go:174] Got controller instance update massage. Updated Controller Type Deployment, current controller instance type Deployment, key 9223372036854775807
> E0904 22:15:30.252878       1 controller_framework.go:363] Current instance not in registry. Controller type Deployment, instance id deployment-543f0343-d5bb-4b74-81e1-848a429f6958, key 9223372036854775807. Needs restart
> I0904 22:15:30.252974       1 controller_framework.go:174] Got controller instance update massage. Updated Controller Type Deployment, current controller instance type ReplicaSet, key 9223372036854775807
> ```
> 
> logs can be found under GCP project: workload-controller-manager:
> 
> ```
> sonya-useast1:  /home/sonyali/logs/perf-test/gce-10000/arktos/0904-node10k-3a2c1e 
> ```

This time it is caused by different issue: API server (10.40.3.231. service group 0) seems having issue and clients lost connection to it. It is possible that wcm could not renew its lease at this time and starting to report problem. 

There are a few action items that we can follow:
1. Check whether the service group we lost at such time are the same. (It is possible it is always service group 0 as the host is most heavily loaded)
2. In WC, upon health report, if it failed to update. Retry/recreate with same id.

51345 I0904 22:05:10.411678       1 update.go:81] Update APIServer Config from [map[0:{Addresses:[{IP:10.40.3.231 Hostname: NodeName:<nil> TargetRef:nil}] NotReadyAddresses:[] Ports:[{Name:https Port:443 Protocol:TCP}] Se      rviceGroupId:0} 1:{Addresses:[{IP:10.40.3.232 Hostname: NodeName:<nil> TargetRef:nil}] NotReadyAddresses:[] Ports:[{Name:https Port:443 Protocol:TCP}] ServiceGroupId:1} 2:{Addresses:[{IP:10.40.3.233 Hostname: NodeNa      me:<nil> TargetRef:nil}] NotReadyAddresses:[] Ports:[{Name:https Port:443 Protocol:TCP}] ServiceGroupId:2}]] to [map[1:{Addresses:[{IP:10.40.3.232 Hostname: NodeName:<nil> TargetRef:nil}] NotReadyAddresses:[] Ports:      [{Name:https Port:443 Protocol:TCP}] ServiceGroupId:1} 2:{Addresses:[{IP:10.40.3.233 Hostname: NodeName:<nil> TargetRef:nil}] NotReadyAddresses:[] Ports:[{Name:https Port:443 Protocol:TCP}] ServiceGroupId:2}]]

51513 I0904 22:05:10.413750       1 storage_client.go:168] Reset restClients. length 3 -> 2
51514 I0904 22:05:10.413772       1 apps_client.go:199] Reset restClients. length 3 -> 2
51515 I0904 22:05:10.413780       1 node_client.go:159] Reset restClients. length 3 -> 2
